package mapp;
import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import javax.swing.*;
import mapp.jplHome;
import mapp.JMain;

public class jplLogin extends JPanel {

    final int pWidth = 420;
    final int pHeight = 230;
    JMenuBar bar;
    JMenu search;
    JMenuItem reg;
    JPanel home;
    
    
    public jplLogin(JPanel jplMain, JMenuBar bar,JMenuItem reg, JMenu search) {
        initComponents();
        this.setSize(pWidth,pHeight);
        int x = (jplMain.getWidth()-pWidth)/2;
        int y = (jplMain.getHeight()-pHeight)/2;
        this.setLocation(x,y);
        this.bar=bar;
        this.reg=reg;
        this.search=search;
        this.home=jplMain;
        this.bar.setVisible(false);
        this.reg.setVisible(false);
       
        this.setVisible(true);
        if (utility.DBconnection.getStatus() == true){
            tfIPAddress.setEnabled(false);
            bnConnect.setEnabled(false);
            bnLogin.setEnabled(true);
            tfIPAddress.setText(utility.IPaddress.getAddress());
        }else{
            tfIPAddress.setEnabled(true);
            bnConnect.setEnabled(true);
            bnLogin.setEnabled(false);
        }
    }
    
    public void displayForm(JPanel jp){
        home.remove(jp);
        home.add(jp);
        home.validate();
        home.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        bnLogin = new javax.swing.JButton();
        bnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfIPAddress = new javax.swing.JTextField();
        bnConnect = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username:");

        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordKeyPressed(evt);
            }
        });

        bnLogin.setBackground(new java.awt.Color(255, 255, 255));
        bnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-User-Interface-Login-icon.png"))); // NOI18N
        bnLogin.setText("Login");
        bnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLoginActionPerformed(evt);
            }
        });
        bnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bnLoginKeyPressed(evt);
            }
        });

        bnCancel.setBackground(new java.awt.Color(255, 255, 255));
        bnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-exit Windows-Turn-Off-icon.png"))); // NOI18N
        bnCancel.setText("Cancel");
        bnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("IP Address:");

        bnConnect.setBackground(new java.awt.Color(255, 255, 255));
        bnConnect.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-connect-icon.png"))); // NOI18N
        bnConnect.setText("Connect");
        bnConnect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnConnectActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/login-form-App-konsole-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bnLogin)
                                    .addGap(66, 66, 66)
                                    .addComponent(bnCancel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnCancel)
                            .addComponent(bnLogin)))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnLoginActionPerformed
     if (tfUsername.getText().isEmpty() || pfPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Complete all fieds");
            return;
        }
        String username = tfUsername.getText();
        String pass = pfPassword.getText();
        String password="";
        String sLevel="";
        String s = "select password, level from account where Username='"+username+"'";
        try{
            ResultSet rs = utility.DBconnection.getStatement().executeQuery(s);
            while(rs.next()){
                password=rs.getString("password");
                sLevel = rs.getString("level");
            }
            
            if (pass.equals(password)){
                this.setVisible(false);
                this.bar.setVisible(true);
                
                displayForm(new jplHome(this.home, sLevel));
                if (sLevel.equals("ADMIN")){
                    this.search.setVisible(true);
                    this.reg.setVisible(true);
                    
            
                }else if (sLevel.equals("MANAGER")){
                    this.search.setVisible(true);
                    this.reg.setVisible(false);
                 
                }else if (sLevel.equals("STAFF")){
                    this.search.setVisible(false);
                    this.reg.setVisible(false);
                    
                }
               
            }else{
                JOptionPane.showMessageDialog(null,"Password Mismatch");
                pfPassword.setText("");
            }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
            tfUsername.setText("");
            pfPassword.setText("");
        }
        
    }//GEN-LAST:event_bnLoginActionPerformed

    private void bnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bnCancelActionPerformed

    private void bnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            bnLogin.doClick();
        }
    }//GEN-LAST:event_bnLoginKeyPressed

    private void pfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            bnLogin.doClick();
        }
    }//GEN-LAST:event_pfPasswordKeyPressed

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        tfUsername.setText(tfUsername.getText().toUpperCase());
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void bnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnConnectActionPerformed
        utility.DBconnection.Connection(tfIPAddress.getText().trim());
        if (utility.DBconnection.getStatus()== true){
            tfIPAddress.setEnabled(false);
            bnConnect.setEnabled(false);
            bnLogin.setEnabled(true);
            //saving
            utility.IPaddress.saveAddress(tfIPAddress.getText());
        }else{
            tfIPAddress.setEnabled(true);
            bnConnect.setEnabled(true);
            bnLogin.setEnabled(false);
        }
    }//GEN-LAST:event_bnConnectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCancel;
    private javax.swing.JButton bnConnect;
    private javax.swing.JButton bnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfIPAddress;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
