
package mapp;
import java.sql.ResultSet;
import javax.swing.*;
import com.sun.glass.events.KeyEvent;
import net.proteanit.sql.DbUtils;

public class jplUsers extends JPanel {

    final int pWidth = 850;
    final int pHeight = 410;
    JMenuItem gohome;
    
    /**
     * Creates new form jplRegistration
     * @param jplMain
     */
    public jplUsers(JPanel jplMain, JMenuItem gohome) {
        initComponents();
        this.setSize(pWidth,pHeight);
        int x = (jplMain.getWidth()-pWidth)/2;
        int y = (jplMain.getHeight()-pHeight)/2;
        this.setLocation(x,y);
        this.setVisible(true);
        this.gohome=gohome;
        initialization();
        filltable();
    }

    private void initialization(){
        bnAddNew.setEnabled(true);
        bnSave.setEnabled(false);
        bnSearch.setEnabled(true);
        bnSearch.setText("Search");
        bnDelete.setEnabled(false);
        tfUsername.setEditable(true);
        tfFName.setEditable(false);
        tfLName.setEditable(false);
        cbLevel.setEnabled(false);
        pfPassword.setEditable(false);
        pfConfirmPass.setEditable(false);
        utility.Utility.universalCode=0; 
    }
    private void filltable(){
        String query="select Username, Fname, Lname, level from account";
        try{
            ResultSet rs = utility.DBconnection.getStatement().executeQuery(query);
            jtUsers.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfFName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbLevel = new javax.swing.JComboBox();
        pfPassword = new javax.swing.JPasswordField();
        pfConfirmPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsers = new javax.swing.JTable();
        bnSearch = new javax.swing.JButton();
        bnDelete = new javax.swing.JButton();
        bnAddNew = new javax.swing.JButton();
        bnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bnClose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfLName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-User-Executive-Green-icon.png"))); // NOI18N
        jLabel1.setText("User");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username:");

        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("First Name:");
        jLabel3.setToolTipText("");

        tfFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFNameFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Level:");
        jLabel5.setToolTipText("");

        cbLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User Level", "STAFF", "MANAGER", "ADMIN" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Confirm Password:");
        jLabel6.setToolTipText("");

        jtUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsersMouseClicked(evt);
            }
        });
        jtUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtUsersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtUsers);

        bnSearch.setBackground(new java.awt.Color(255, 255, 255));
        bnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-search-icon.png"))); // NOI18N
        bnSearch.setText("Search");
        bnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSearchActionPerformed(evt);
            }
        });

        bnDelete.setBackground(new java.awt.Color(255, 255, 255));
        bnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-trash-icon.png"))); // NOI18N
        bnDelete.setText("Delete");
        bnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        bnAddNew.setBackground(new java.awt.Color(255, 255, 255));
        bnAddNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/Button-Add-icon.png"))); // NOI18N
        bnAddNew.setText("Add New");
        bnAddNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddNewActionPerformed(evt);
            }
        });

        bnSave.setBackground(new java.awt.Color(255, 255, 255));
        bnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-Save-icon.png"))); // NOI18N
        bnSave.setText("Save");
        bnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSaveActionPerformed(evt);
            }
        });

        bnClose.setBackground(new java.awt.Color(255, 255, 255));
        bnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-close blue-icon.png"))); // NOI18N
        bnClose.setText("Close");
        bnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCloseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapp/button-User-Group-icon.png"))); // NOI18N
        jLabel7.setText("All Users");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Last Name:");
        jLabel8.setToolTipText("");

        tfLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bnSearch)
                                    .addGap(18, 18, 18)
                                    .addComponent(bnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bnAddNew)
                                    .addGap(18, 18, 18)
                                    .addComponent(bnDelete)
                                    .addGap(21, 21, 21)
                                    .addComponent(bnClose))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(20, 20, 20)
                                    .addComponent(pfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfFName)
                                    .addGap(5, 5, 5)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnSearch)
                            .addComponent(bnAddNew)
                            .addComponent(bnClose)
                            .addComponent(bnSave)
                            .addComponent(bnDelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean validation(){
        if (tfUsername.getText().isEmpty() || tfFName.getText().isEmpty() || tfLName.getText().isEmpty() ||
                cbLevel.getSelectedIndex()==0 || pfPassword.getText().isEmpty() ||
                pfConfirmPass.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }
    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        tfUsername.setText(tfUsername.getText().toUpperCase());
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFNameFocusLost
        tfFName.setText(tfFName.getText().toUpperCase());
    }//GEN-LAST:event_tfFNameFocusLost

    private void bnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddNewActionPerformed
        bnAddNew.setEnabled(false);
        bnSave.setEnabled(true);
        bnSearch.setEnabled(false);
        bnDelete.setEnabled(false);
        tfUsername.setEditable(true);
        tfFName.setEditable(true);
        tfLName.setEditable(true);
        cbLevel.setEnabled(true);
        pfPassword.setEditable(true);
        pfConfirmPass.setEditable(true);
        utility.Utility.universalCode=1;
    }//GEN-LAST:event_bnAddNewActionPerformed

    private void bnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCloseActionPerformed
        if (utility.Utility.universalCode == 1){
            int res=JOptionPane.showConfirmDialog(null, "Do you want to save changes?","Warning",JOptionPane.YES_NO_OPTION);
            if (res==JOptionPane.YES_OPTION){
                if (bnSearch.getText().equals("Update")){
                    bnSearch.doClick();
                }else{
                    bnSave.doClick();
                }
            }else{
                this.gohome.doClick();
            }
        }else{
            this.gohome.doClick();
        }
    }//GEN-LAST:event_bnCloseActionPerformed

    private void bnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSaveActionPerformed
        if (!validation()){
            JOptionPane.showMessageDialog(null,"Complete all fields");
            return;
        }
        if (!(pfPassword.getText().equals(pfConfirmPass.getText()))){
            JOptionPane.showMessageDialog(null, "Passwords should match");
            pfPassword.setText("");
            pfConfirmPass.setText("");
            return;
        }
        String s="insert into account values ('"+tfUsername.getText()+"','"+tfFName.getText()+"','"+tfLName.getText()+"','"+cbLevel.getSelectedItem()+"','"+pfPassword.getText()+"')";
        try{
           if(utility.DBconnection.getStatement().executeUpdate(s)>0){
               JOptionPane.showMessageDialog(null, "Save is Successful");
               tfUsername.setText("");
               tfFName.setText("");
               tfLName.setText("");
               cbLevel.setSelectedIndex(0);
               pfPassword.setText("");
               pfConfirmPass.setText("");
               initialization();
               filltable();
           }else{
               JOptionPane.showMessageDialog(null, "Could not save data");
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_bnSaveActionPerformed

    private void bnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSearchActionPerformed
        if (bnSearch.getText().equals("Search")){
            if (tfUsername.getText().isEmpty()){
               JOptionPane.showMessageDialog(null,"Enter Username");
               return;
            }
            
            String username = tfUsername.getText().trim();
            String s = "select Name, level from account where Username='"+username+"'";
            try{
                ResultSet rs = utility.DBconnection.getStatement().executeQuery(s);
                while(rs.next()){
                    tfUsername.setText(username);
                    tfFName.setText(rs.getString("Fname"));
                    tfLName.setText(rs.getString("Lname"));
                    cbLevel.setSelectedItem(rs.getString("level"));
                }
                tfUsername.setEditable(false);
                tfFName.setEditable(false);
                tfLName.setEditable(false);
                cbLevel.setEnabled(false);
                pfPassword.setEditable(false);
                pfConfirmPass.setEditable(false);
                bnSave.setEnabled(false);
                bnDelete.setEnabled(true);
                bnAddNew.setEnabled(false);
                bnSearch.setText("Edit");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
                tfUsername.setText("");
            }
        }else if (bnSearch.getText().equals("Edit")){
            tfFName.setEditable(true);
            tfLName.setEditable(true);
            cbLevel.setEnabled(true);
            bnSearch.setText("Update");
            utility.Utility.universalCode=1;
        }else if (bnSearch.getText().equals("Update")){
            String s= "update account set Fname='"+tfFName.getText()+"', Lname='"+tfLName.getText()+"', level='"+cbLevel.getSelectedItem()+"' where Username='"+tfUsername.getText()+"'";
            try{
                if(utility.DBconnection.getStatement().executeUpdate(s)>0){
                    JOptionPane.showMessageDialog(null, "Update is Successful");
                    tfUsername.setText("");
                    tfFName.setText("");
                    tfLName.setText("");
                    cbLevel.setSelectedIndex(0);
                    pfPassword.setText("");
                    pfConfirmPass.setText("");
                    initialization();
                    filltable();
                }else{
                    JOptionPane.showMessageDialog(null, "Could not update data");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
             }
        }
    }//GEN-LAST:event_bnSearchActionPerformed

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        String s= "delete from account where Username='"+tfUsername.getText().trim()+"'";
            try{
                if(utility.DBconnection.getStatement().executeUpdate(s)>0){
                    JOptionPane.showMessageDialog(null, "Delete is Successful");
                    tfUsername.setText("");
                    tfFName.setText("");
                    tfLName.setText("");
                    cbLevel.setSelectedIndex(0);
                    pfPassword.setText("");
                    pfConfirmPass.setText("");
                    initialization();
                    filltable();
                }else{
                    JOptionPane.showMessageDialog(null, "Could not delete data");
                }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
             }
    }//GEN-LAST:event_bnDeleteActionPerformed

    private void jtUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsersMouseClicked
        try{
            int row=jtUsers.getSelectedRow();
            String TableClick=jtUsers.getModel().getValueAt(row, 0).toString();
            String query="select * from account where Username='"+TableClick+"'";
            
            ResultSet rs = utility.DBconnection.getStatement().executeQuery(query);
            while(rs.next()){
                    tfUsername.setText(rs.getString("Username"));
                    tfFName.setText(rs.getString("Fname"));
                    tfLName.setText(rs.getString("Lname"));
                    cbLevel.setSelectedItem(rs.getString("level"));
                }
                tfUsername.setEditable(false);
                tfFName.setEditable(false);
                tfLName.setEditable(false);
                cbLevel.setEnabled(false);
                pfPassword.setEditable(false);
                pfConfirmPass.setEditable(false);
                bnSave.setEnabled(false);
                bnDelete.setEnabled(true);
                bnAddNew.setEnabled(false);
                bnSearch.setText("Edit");
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_jtUsersMouseClicked

    private void jtUsersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsersKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN||evt.getKeyCode() == KeyEvent.VK_UP){
          try{
            int row=jtUsers.getSelectedRow();
            String TableClick=jtUsers.getModel().getValueAt(row, 0).toString();
            String query="select * from account where Username='"+TableClick+"'";
            
            ResultSet rs = utility.DBconnection.getStatement().executeQuery(query);
            while(rs.next()){
                    tfUsername.setText(rs.getString("Username"));
                    tfFName.setText(rs.getString("Fname"));
                    tfLName.setText(rs.getString("Lname"));
                    cbLevel.setSelectedItem(rs.getString("level"));
                }
                tfUsername.setEditable(false);
                tfFName.setEditable(false);
                tfLName.setEditable(false);
                cbLevel.setEnabled(false);
                pfPassword.setEditable(false);
                pfConfirmPass.setEditable(false);
                bnSave.setEnabled(false);
                bnDelete.setEnabled(true);
                bnAddNew.setEnabled(false);
                bnSearch.setText("Edit");
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }  
        }
    }//GEN-LAST:event_jtUsersKeyReleased

    private void tfLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLNameFocusLost
        tfLName.setText(tfLName.getText().toUpperCase());
    }//GEN-LAST:event_tfLNameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAddNew;
    private javax.swing.JButton bnClose;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnSave;
    private javax.swing.JButton bnSearch;
    private javax.swing.JComboBox cbLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtUsers;
    private javax.swing.JPasswordField pfConfirmPass;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfFName;
    private javax.swing.JTextField tfLName;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
